name: Testing Workflow 2 

on: 
  workflow_dispatch:
  

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          name: zmackiv/bachelor_project
          ref: main
          
      - name: Git log
        run: git log
          
