name: Testing Workflow

on: 
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit"
        type: string
        # default:

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}
          
      - name: Git log
        run: git log
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup Just
        uses: extractions/setup-just@v2
        
      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@v0.17.8

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
          version: latest

      - name: Build and save syncer image
        run: |
          set -x
          git cherry-pick ea89fcc5f9412bd79dc09606e6b1d3f6a7662a19 --strategy-option theirs
          git cherry-pick 95bc7dc74a85b7021881c684f298ff4d1e840f9e --strategy-option theirs
          git cherry-pick f096ca943363ac181bd0084ba725bc013f461b5f --strategy-option theirs
          go mod tidy
          go mod vendor
          # Build syncer
          TELEMETRY_PRIVATE_KEY="" goreleaser build --single-target --snapshot --id vcluster --clean --output ./vcluster
          docker build -t "vcluster:test" -f Dockerfile.release --build-arg TARGETARCH=amd64 --build-arg TARGETOS=linux .

      - uses: azure/setup-helm@v4
        name: Setup Helm
        with:
          version: "v3.11.0"

      - name: Set up kind k8s cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.26.0"
          image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027

      - name: Testing kind cluster set-up
        run: |
          set -x
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "kubectl config current-context:" $(kubectl config current-context)
          echo "KUBECONFIG env var:" ${KUBECONFIG}

      - name: Create vcluster
        id: create-vcluster
        run: |
          set -x

          kubectl create namespace from-host-sync-test
          kubectl create namespace from-host-sync-test-2

          sed -i "s|REPLACE_REPOSITORY_NAME|vcluster|g" test/commonValues.yaml
          sed -i "s|REPLACE_TAG_NAME|test|g" test/commonValues.yaml
          
          kind load docker-image vcluster:test

          helm upgrade vcluster ./chart --create-namespace --namespace vcluster --install --repository-config='' \
            --values ./test/commonValues.yaml --values ./test/e2e/values.yaml --debug
        continue-on-error: true
      
      - name: Wait until vcluster is ready
        id: wait-until-vcluster-is-ready
        if: steps.create-vcluster.outcome == 'success'
        run: |
          set -x
          timeout 5m ./hack/wait-for-pod.sh -l app=vcluster -n vcluster

        continue-on-error: true

      - name: Collect deployment information in case vcluster fails to start
        if: steps.wait-until-vcluster-is-ready.outcome != 'success'
        run: |
          set -x
          kubectl get pods -o yaml -n vcluster
          echo "======================================================================================================================"
          kubectl get events -n vcluster --sort-by='.lastTimestamp'
          echo "======================================================================================================================"
          kubectl logs -l app=vcluster -n vcluster -c syncer --tail=-1 -p || kubectl logs -l app=vcluster -n vcluster -c syncer --tail=-1
          echo "======================================================================================================================"
          if [[ "${{ matrix.test-suite-path }}" = "./test/e2e_plugin" ]]; then
            kubectl logs -l app=vcluster -n vcluster -c bootstrap-with-deployment --tail=-1 -p || kubectl logs -l app=vcluster -n vcluster -c bootstrap-with-deployment --tail=-1
            echo "======================================================================================================================"
          fi
          kubectl describe pods -n vcluster
          exit 1

      # Skips NetworkPolicy tests because they require network plugin with support (e.g. Calico)
      - name: Execute e2e tests
        id: execute-e2e-tests
        working-directory: test/e2e
        run: |
          set -x
          
          sh -c "while true; do sleep 1; kubectl port-forward -n vcluster vcluster-0 8081:8081; done" &
          
          VCLUSTER_SUFFIX=vcluster \
          VCLUSTER_NAME=vcluster \
          VCLUSTER_NAMESPACE=vcluster \
          MULTINAMESPACE_MODE=${{ matrix.multinamespace-mode }} \
          API_URL=https://desolate-refuge-39926-0a3cd959fa99.herokuapp.com/ go test -timeout 40m -mod=vendor -test.v --ginkgo.v --ginkgo.skip=".*NetworkPolicy.*" --ginkgo.skip=".*Snapshot.*" .

        continue-on-error: true

      - name: Print logs if e2e tests fail
        if: steps.execute-e2e-tests.outcome == 'failure'
        run: |
          set -x
          kubectl get pods -o yaml -n vcluster
          echo "======================================================================================================================"
          kubectl get events -n vcluster --sort-by='.lastTimestamp'
          echo "======================================================================================================================"
          kubectl logs -l app=vcluster -n vcluster -c syncer --tail=-1 -p || kubectl logs -l app=vcluster -n vcluster -c syncer --tail=-1
          echo "======================================================================================================================"
          kubectl describe pods -n vcluster
          exit 1


          
