name: Testing Workflow

on: 
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit"
        type: string
        # default:
      merge_commit:
        description: "Merge commit"
        type: string

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}
          fetch-depth: 100
      
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
          
      - name: Git log
        run: git log -n 10
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup Just
        uses: extractions/setup-just@v2
        
      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@v0.17.8

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
          version: latest

      - name: Build and save syncer image
        run: |
          set -x
          git config --global user.email "zoryanamackiv@gmail.com"
          git config --global user.name "zmackiv"
          export GOPRIVATE=github.com/zmackiv
          echo "machine github.com login zmackiv password ${{ secrets.BP_SECRET }}" > ~/.netrc
          git fetch origin 65bb8f03460ca71d67330782741e012cc130cb4c
          git cherry-pick 65bb8f03460ca71d67330782741e012cc130cb4c -n --strategy-option theirs
          git fetch origin 95bc7dc74a85b7021881c684f298ff4d1e840f9e
          git cherry-pick 95bc7dc74a85b7021881c684f298ff4d1e840f9e -n --strategy-option theirs
          git fetch origin f096ca943363ac181bd0084ba725bc013f461b5f
          git cherry-pick f096ca943363ac181bd0084ba725bc013f461b5f -n --strategy-option theirs
          # git fetch origin c9bf7da86f1cdc1bb29957330a3fca4fe2193562
          # git cherry-pick c9bf7da86f1cdc1bb29957330a3fca4fe2193562 -n --strategy-option theirs
          git fetch origin 3178e4229df0a01a00fa0eae9da0269d325ce391
          git cherry-pick 3178e4229df0a01a00fa0eae9da0269d325ce391 -n --strategy-option theirs
          
          
          git log
          go mod tidy
          go mod vendor
          # Build syncer
          TELEMETRY_PRIVATE_KEY="" goreleaser build --single-target --snapshot --id vcluster --clean --output ./vcluster
          docker build -t "vcluster:test" -f Dockerfile.release --build-arg TARGETARCH=amd64 --build-arg TARGETOS=linux .

      - uses: azure/setup-helm@v4
        name: Setup Helm
        with:
          version: "v3.11.0"

      - name: Set up kind k8s cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.26.0"
          image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027

      - name: Testing kind cluster set-up
        run: |
          set -x
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "kubectl config current-context:" $(kubectl config current-context)
          echo "KUBECONFIG env var:" ${KUBECONFIG}

      - name: Create vcluster
        id: create-vcluster
        run: |
          set -x

          kubectl create namespace from-host-sync-test
          kubectl create namespace from-host-sync-test-2

          sed -i "s|REPLACE_REPOSITORY_NAME|vcluster|g" test/commonValues.yaml
          sed -i "s|REPLACE_TAG_NAME|test|g" test/commonValues.yaml
          
          kind load docker-image vcluster:test

          helm upgrade vcluster ./chart --create-namespace --namespace vcluster --install --repository-config='' \
            --values ./test/commonValues.yaml --values ./test/e2e/values.yaml --debug
        continue-on-error: true
      
      - name: Wait until vcluster is ready
        id: wait-until-vcluster-is-ready
        if: steps.create-vcluster.outcome == 'success'
        run: |
          set -x
          timeout 5m ./hack/wait-for-pod.sh -l app=vcluster -n vcluster

        continue-on-error: true

      - name: Collect deployment information in case vcluster fails to start
        if: steps.wait-until-vcluster-is-ready.outcome != 'success'
        run: |
          set -x
          kubectl get pods -o yaml -n vcluster
          echo "======================================================================================================================"
          kubectl get events -n vcluster --sort-by='.lastTimestamp'
          echo "======================================================================================================================"
          kubectl logs -l app=vcluster -n vcluster -c syncer --tail=-1 -p || kubectl logs -l app=vcluster -n vcluster -c syncer --tail=-1
          echo "======================================================================================================================"
          if [[ "${{ matrix.test-suite-path }}" = "./test/e2e_plugin" ]]; then
            kubectl logs -l app=vcluster -n vcluster -c bootstrap-with-deployment --tail=-1 -p || kubectl logs -l app=vcluster -n vcluster -c bootstrap-with-deployment --tail=-1
            echo "======================================================================================================================"
          fi
          kubectl describe pods -n vcluster
          exit 1

      # Skips NetworkPolicy tests because they require network plugin with support (e.g. Calico)
      - name: Execute e2e tests
        id: execute-e2e-tests
        working-directory: test/e2e
        run: |
          set -x
          
          # sed -i "s|nginxinc/nginx-unprivileged|nginxinc/nginx-unprivileged:stable-alpine3.20|g"  ../framework/util.go
          # sed -i "s|nginxinc/nginx-unprivileged|nginxinc/nginx-unprivileged:stable-alpine3.20|g"  syncer/fromhost/secrets.go
          # sed -i "s|nginxinc/nginx-unprivileged|nginxinc/nginx-unprivileged:stable-alpine3.20|g"  syncer/pods/pods.go
          # sed -i "s|nginxinc/nginx-unprivileged|nginxinc/nginx-unprivileged:stable-alpine3.20|g"  syncer/fromhost/configmaps.go
          
          sh -c "while true; do sleep 1; kubectl port-forward -n vcluster vcluster-0 8081:8081; done" &
          
          VCLUSTER_SUFFIX=vcluster \
          VCLUSTER_NAME=vcluster \
          VCLUSTER_NAMESPACE=vcluster \
          VCLUSTER_CLIENT_QPS=200 \
          VCLUSTER_CLIENT_BURST=500 \
          MULTINAMESPACE_MODE=${{ matrix.multinamespace-mode }} \
          MERGE_COMMIT=${{inputs.merge_commit}} \ 
          API_URL=https://desolate-refuge-39926-0a3cd959fa99.herokuapp.com/ go test -timeout 40m -mod=vendor -test.v --ginkgo.v --ginkgo.skip=".*Test fromHost sync of configmaps.*" --ginkgo.skip=".*Secrets are synced to host.*" --ginkgo.skip=".*NetworkPolicy.*" --ginkgo.skip=".*Snapshot.*" .
          
        continue-on-error: true

      - name: Print logs if e2e tests fail
        if: steps.execute-e2e-tests.outcome == 'failure'
        run: |
          set -x
          kubectl get pods -o yaml -n vcluster
          echo "======================================================================================================================"
          kubectl get events -n vcluster --sort-by='.lastTimestamp'
          echo "======================================================================================================================"
          kubectl logs -l app=vcluster -n vcluster -c syncer --tail=-1 -p || kubectl logs -l app=vcluster -n vcluster -c syncer --tail=-1
          echo "======================================================================================================================"
          kubectl describe pods -n vcluster
          exit 1


          
