name: Testing Workflow 2 

on: 
  workflow_dispatch:
  

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Clone private repo A
        env:
          TOKEN: ${{ secrets.SECRET_TO_BP }}
        run: |
          git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"
          git clone https://github.com/zmackiv/bachelor_project.git
          
      - name: Git log
        run: git log
          
